package pl.stalostech.jms;

import javax.jms.JMSException;
import javax.jms.Message;
import javax.jms.Queue;
import javax.jms.Session;
import javax.jms.TextMessage;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jms.core.JmsTemplate;
import org.springframework.jms.core.MessageCreator;
import org.springframework.stereotype.Service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import pl.stalostech.autogenerated.xsd.model.Configuration;

@Service
public class BLJMSClient implements JMSClient {

	@Autowired
	private JmsTemplate jmsTemplate;

	@Autowired
	private Queue blQueue;

	@Override
	public void sendConfigurationMessage(Configuration configuration) {
		jmsTemplate.send(blQueue, new MessageCreator() {
			@Override
			public Message createMessage(Session session) throws JMSException {

				TextMessage message = session.createTextMessage();
				ObjectMapper mapper = new ObjectMapper();
				try {
					message.setText(mapper.writeValueAsString(configuration));
				} catch (JsonProcessingException e) {
					throw new JMSException("Can not convert configuration to JSON format.");
				}

				return message;
			}
		});
	}

}
