package pl.stalostech.configuration;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ws.server.endpoint.annotation.Endpoint;
import org.springframework.ws.server.endpoint.annotation.PayloadRoot;
import org.springframework.ws.server.endpoint.annotation.RequestPayload;
import org.springframework.ws.server.endpoint.annotation.ResponsePayload;

import pl.stalostech.autogenerated.xsd.model.Configuration;
import pl.stalostech.autogenerated.xsd.model.GetConfigurationRequest;
import pl.stalostech.autogenerated.xsd.model.GetConfigurationResponse;
import pl.stalostech.autogenerated.xsd.model.SaveConfigurationRequest;
import pl.stalostech.autogenerated.xsd.model.SaveConfigurationResponse;
import pl.stalostech.autogenerated.xsd.model.Status;
import pl.stalostech.repository.ConfigurationRepository;

@Endpoint
public class ConfigurationEndpoint {
	
	private static final String NAMESPACE_URI = "http://stalostech.pl/autogenerated/xsd/model";
	
	@Autowired
	private ConfigurationRepository repository;

	@PayloadRoot(namespace = NAMESPACE_URI, localPart = "getConfigurationRequest")
	@ResponsePayload
	public GetConfigurationResponse getCountry(@RequestPayload GetConfigurationRequest request) {
		GetConfigurationResponse response = new GetConfigurationResponse();
		
		System.out.println(repository.findAll());
		System.out.println(repository.findOne("412662"));
		
		response.setConfiguration(new Configuration());
		return response;
	}
	
	@PayloadRoot(namespace = NAMESPACE_URI, localPart = "saveConfigurationRequest")
	@ResponsePayload
	public SaveConfigurationResponse getCountry(@RequestPayload SaveConfigurationRequest request) {
		SaveConfigurationResponse response = new SaveConfigurationResponse();
		response.setStatus(Status.OK);
		return response;
	}
}
