//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 10:39:05 PM CEST 
//


package pl.stalostech.autogenerated.xsd.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for model.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="model"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CAR"/&gt;
 *     &lt;enumeration value="LOGO"/&gt;
 *     &lt;enumeration value="NEW_LOGO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "model")
@XmlEnum
public enum Model {

    CAR,
    LOGO,
    NEW_LOGO;

    public String value() {
        return name();
    }

    public static Model fromValue(String v) {
        return valueOf(v);
    }

}
