package pl.stalostech.endpoint;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ws.server.endpoint.annotation.Endpoint;
import org.springframework.ws.server.endpoint.annotation.PayloadRoot;
import org.springframework.ws.server.endpoint.annotation.RequestPayload;
import org.springframework.ws.server.endpoint.annotation.ResponsePayload;

import pl.stalostech.autogenerated.xsd.model.GetConfigurationRequest;
import pl.stalostech.autogenerated.xsd.model.GetConfigurationResponse;
import pl.stalostech.autogenerated.xsd.model.SaveConfigurationRequest;
import pl.stalostech.autogenerated.xsd.model.SaveConfigurationResponse;
import pl.stalostech.autogenerated.xsd.model.Status;
import pl.stalostech.service.ConfigurationService;

@Endpoint
public class ConfigurationEndpoint {
	
	private static final String NAMESPACE_URI = "http://stalostech.pl/autogenerated/xsd/model";
	
	@Autowired
	private ConfigurationService configurationService;
	
	@PayloadRoot(namespace = NAMESPACE_URI, localPart = "getConfigurationRequest")
	@ResponsePayload
	public GetConfigurationResponse getConfiguration(@RequestPayload GetConfigurationRequest request) {
		GetConfigurationResponse response = new GetConfigurationResponse();
		response.setConfiguration(configurationService.getConfigurationFromDb());
		return response;
	}
	
	@PayloadRoot(namespace = NAMESPACE_URI, localPart = "saveConfigurationRequest")
	@ResponsePayload
	public SaveConfigurationResponse saveConfiguration(@RequestPayload SaveConfigurationRequest request) {
		configurationService.storeConfigurationInDb(request.getConfiguration());
		SaveConfigurationResponse response = new SaveConfigurationResponse();
		response.setStatus(Status.OK);
		return response;
	}
}
