package pl.stalostech.service;

import org.dozer.DozerBeanMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.stereotype.Service;

import pl.stalostech.autogenerated.xsd.model.Configuration;
import pl.stalostech.model.ConfigurationModel;
import pl.stalostech.repository.ConfigurationRepository;

/**
 * Service for configuration. 
 * @author Bartosz Wysocki
 */
@Service
public class ConfigurationService {
	
	private final static String DOZER_SECTION = "configuration";
	
	@Autowired
	private ConfigurationRepository repository;
	
	@Autowired
    private MongoTemplate mongoTemplate;
	
	@Autowired 
	private DozerBeanMapper dozer;
	
	public Configuration getConfigurationFromDb() {
		Configuration r = new Configuration();
		dozer.map(repository.findConfiguration(), r, DOZER_SECTION);
		return r;
	}
	
	public void storeConfigurationInDb(Configuration configuration) {
		ConfigurationModel dbRecord = repository.findConfiguration();
		dozer.map(configuration, dbRecord, DOZER_SECTION);
		mongoTemplate.save(dbRecord);
	}
	
}
