package pl.stalostech.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

import pl.stalostech.autogenerated.xsd.model.Configuration;
import pl.stalostech.jms.JMSClient;
import pl.stalostech.model.ConfigurationModel;
import pl.stalostech.repository.ConfigurationRepository;

/**
 * Service for configuration.
 * 
 * @author Bartosz Wysocki
 */
@Service
public class ConfigurationService {

	public final static String CACHE_NAME = "dbConfiguration";

	@Autowired
	private ConfigurationRepository repository;

	@Autowired
	private DozerMapperService dozerMapperService;

	@Autowired
	private JMSClient jmsClient;

	@Cacheable(CACHE_NAME)
	public Configuration getConfigurationFromDb() {
		return dozerMapperService.mapDbEntityToSoapModel(repository.findConfiguration());
	}

	@CacheEvict(value = CACHE_NAME, allEntries = true)
	public void storeConfigurationInDb(Configuration configuration) {
		ConfigurationModel dbRecord = getAndUpdateDbConfiguration(configuration);
		jmsClient.sendConfigurationMessage(configuration);
		repository.save(dbRecord);
	}

	private ConfigurationModel getAndUpdateDbConfiguration(Configuration configuration) {
		ConfigurationModel dbRecord = repository.findConfiguration();
		dozerMapperService.updateDbEntityWithSoapModel(dbRecord, configuration);
		return dbRecord;
	}

}
