package pl.stalostech.service;

import java.util.Optional;

import org.dozer.DozerBeanMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import pl.stalostech.autogenerated.xsd.model.Configuration;
import pl.stalostech.model.ConfigurationModel;

@Service
public class DozerMapperService {

	public final static String DOZER_SECTION = "configuration";

	@Autowired
	private DozerBeanMapper dozer;

	public Configuration mapDbEntityToSoapModel(final ConfigurationModel dbEntity) {
		Optional<ConfigurationModel> dbEntityOptional = Optional.ofNullable(dbEntity);

		Configuration r = new Configuration();
		if (dbEntityOptional.isPresent()) {
			dozer.map(dbEntity, r, DOZER_SECTION);
		}
		return r;
	}

	public void updateDbEntityWithSoapModel(final ConfigurationModel dbEntity, final Configuration configuration) {
		Optional<ConfigurationModel> dbEntityOptional = Optional.ofNullable(dbEntity);
		Optional<Configuration> configurationOptional = Optional.ofNullable(configuration);

		if (dbEntityOptional.isPresent()) {
			dozer.map(configurationOptional.isPresent() ? configurationOptional.get() : new Configuration(), dbEntity,
					DOZER_SECTION);
		}
	}

}
