package pl.stalostech.testutils;

import org.springframework.stereotype.Service;

import pl.stalostech.autogenerated.xsd.model.Configuration;
import pl.stalostech.autogenerated.xsd.model.Model;
import pl.stalostech.model.ConfigurationModel;

@Service
public class ModelFactory {

	public Configuration getSampleConfiguration() {
		Configuration r = new Configuration();
		r.setFps(30);
		r.setLogoColor("#123456");
		r.setModel(Model.CAR);
		r.setThreshold(20);
		r.setThresholdChecked(false);
		return r;
	}

	public ConfigurationModel getSampleConfigurationModel() {
		ConfigurationModel r = new ConfigurationModel();
		r.setFps(5);
		r.setId("412662");
		r.setLogoColor("#aaabcx");
		r.setModel(1);
		r.setThreshold(30);
		r.setThresholdChecked(true);
		return r;
	}

}
